In [2]:
import numpy as np

In [4]:
rowvector=np.array([33,44,55])
print("Row",rowvector)
columnvector=np.array([[33],[44],[55]])
print("Column",columnvector)

Row [33 44 55]
Column [[33]
 [44]
 [55]]


In [10]:
v1=np.array([23,34,45])
print(v1)
v2=np.array([2,4,8])
print(v2)
sum,sub,mul,div=v1+v2,v1-v2,v1*v2,v1/v2
print("SUM",sum,"SUB",sub,"MUL",mul,"DIV",div,sep="\n")

[23 34 45]
[2 4 8]
SUM
[25 38 53]
SUB
[21 30 37]
MUL
[ 46 136 360]
DIV
[11.5    8.5    5.625]


In [12]:
dotproduct=v1.dot(v2)
dotproduct

542